CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha VARCHAR(100) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    RG CHAR(9) NOT NULL UNIQUE,
    Telefone VARCHAR(15),
    Endereco VARCHAR(255),
    Cidade VARCHAR(100),
    Tipo VARCHAR(50),
    DataNascimento DATE
)

CREATE TABLE ATENDIMENTOS (
    NumeroAtendimento SERIAL PRIMARY KEY,
    UsuarioID INT NOT NULL,
    FisioterapeutaID INT NOT NULL,
    DataAtendimento DATE NOT NULL,
    Horario TIME NOT NULL,
    CID VARCHAR(10) NOT NULL,
    ObsLocal TEXT,
    FOREIGN KEY (UsuarioID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (FisioterapeutaID) REFERENCES USUARIOS(ID)
);


SELECT * FROM USUARIOS

select * FROM ATENDIMENTOS